pub const HTML_ALLOWED_TAGS: [&str; 63] = [
    "address",
    "article",
    "aside",
    "base",
    "basefont",
    "blockquote",
    "body",
    "caption",
    "center",
    "col",
    "colgroup",
    "dd",
    "details",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hr",
    "html",
    "iframe",
    "legend",
    "li",
    "link",
    "main",
    "menu",
    "menuitem",
    "nav",
    "noframes",
    "ol",
    "optgroup",
    "option",
    "p",
    "param",
    "search",
    "section",
    "summary",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "title",
    "tr",
    "track",
    "ul",
];

/// First 5 start/end conditions of HTML blocks
/// in the Commonmark spec
/// they all lack the starting
/// `<` due to how the `Walker` handles characters
pub const SIMPLE_CONDITIONS: [[&str; 2]; 8] = [
    // cond 1
    ["pre", "</pre>"],
    ["script", "</script>"],
    ["style", "</style>"],
    ["textarea", "</textarea>"],
    // cond 2
    ["!--", "-->"],
    // cond 3
    ["?", "?>"],
    // cond 4
    // treat specically
    // after the `!` check for any ascii character
    ["!", ">"],
    // cond 5
    ["![CDATA[", "]]>"],
];
